theme: jekyll-theme-minimal
title: Maslow's Redefinition
description: A Study on Human Needs in Times of Covid
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
